version: "3.1"

services:

  angular:
    build:
      context: ./frontAngular
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    container_name: annuaire-angular

  spring:
    build:
      context: ./annuaire
      dockerfile: Dockerfile
    ports:
      - 8082:8082
      - 8001:8001
    depends_on:
      - db
      - kafka
    container_name: annuaire-spring

  db:
    build:
      context: ./dockerfile/hsqldb
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    container_name: annuaire-hsqldb

  zookeeper:
    build:
      context: ./dockerfile/zookeeper
      dockerfile: Dockerfile
    ports:
      - 2181:2181
    container_name: annuaire-zookeeper

  kafka:
    build:
      context: ./dockerfile/kafka
      dockerfile: Dockerfile
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    hostname: kafka
    links:
      - zookeeper
    container_name: annuaire-kafka

  init-kafka:
    build:
      context: dockerfile/init-kafka
      dockerfile: Dockerfile
    container_name: annuaire-init-kafka

volumes:
  db-data:

