version: "3.1"

services:

  angular:
    build:
      context: ./frontAngular
      dockerfile: Dockerfile
    volumes: # Volume binding
      - ./frontAngular:/usr/src/app
    ports:
      - 4200:4200
    networks:
      - app-tier

  spring:
    build:
      context: ./annuaire
      dockerfile: Dockerfile
    ports:
      - 8082:8082
      - 8001:8001
    restart: "no"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:hsqldb:hsql:/db/test
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
    networks:
      - app-tier

  db:
    image: mitchtalmadge/hsqldb
    environment:
      - HSQLDB_TRACE=true
      - HSQLDB_SILENT=false
      - HSQLDB_USER=sa
      - HSQLDB_PASSWORD=
      - HSQLDB_DATABASE_HOST=localhost
      - HSQLDB_DATABASE_ALIAS=test
    ports:
      - 9001:9001
    volumes:
      - /opt/database
    networks:
      - app-tier

volumes:
  db-data:

networks:
  app-tier:
    driver: bridge
